### ISSUE TITLE
Item frame border is pink

### ISSUE THREAD

**Issue by gozyte** [M3TTA/ParidaeyPack#21]
item frames are made out of sticks so shouldnt be pink

**Comment by M3TTA** [comment]
**note to anyone working on this:** 
the border of the item frame entity seems to be using a cherry wood texture

**Comment by gozyte** [comment]
change models/blocks/item_frame_map to this {
    "parent": "minecraft:block/template_item_frame_map",
    "textures": {
        "particle": "block/oak_planks",
        "wood": "block/oak_planks",
        "back": "block/item_frame"
    }
}

**Comment by M3TTA** [comment]
Can you properly format that please?

use the code block feature

**Comment by M3TTA** [comment]
```{
    "parent": "minecraft:block/template_item_frame_map",
    "textures": {
        "particle": "block/oak_planks",
        "wood": "block/oak_planks",
        "back": "block/item_frame"
    }
}

**Comment by DavvyJonesLocker** [comment]
[ParidaeyPack (2).zip](https://github.com/M3TTA/ParidaeyPack/files/6964688/ParidaeyPack.2.zip)

**Comment by M3TTA** [comment]
> [ParidaeyPack (2).zip](https://github.com/M3TTA/ParidaeyPack/files/6964688/ParidaeyPack.2.zip)

what is this

**Comment by DavvyJonesLocker** [comment]
I added the item frame textures it should just fix the problem

**Comment by M3TTA** [comment]
> I added the item frame textures it should just fix the problem

I applied the fix to the latest main branch and they appear to be unchanged 
![image_2021-08-17_165202](https://user-images.githubusercontent.com/24359403/129798878-e52c661c-72e6-454f-88cf-ba236dc990f0.png)

**Comment by DavvyJonesLocker** [comment]
alright ive figured out why its pink the item frame texture uses the edges of the birch wood oak texture as the sticks

**Comment by DavvyJonesLocker** [comment]
> alright ive figured out why its pink the item frame texture uses the edges of the birch wood oak texture as the sticks

we could replace the cherry wood with the default birch and replace another wood type with cherry

**Comment by M3TTA** [comment]
fixed, will be added into the next release
